on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider
      - run: npm run lint
